package com.hushbunny.app.ui.enumclass

enum class FilterType {
    NO_SELECTION, DATE, MONTH, YEAR, DATE_RANGE, MONTH_RANGE, YEAR_RANGE,
    FROM_DATE_RANGE, TO_DATE_RANGE, FROM_MONTH_RANGE, TO_MONTH_RANGE, FROM_YEAR_RANGE, TO_YEAR_RANGE
}