package com.hushbunny.app.ui.enumclass

enum class NotificationType {
    WELCOME_NOTIFICATION,
    ADD_KID,
    ADD_KID_WITHOUT_ADDED_SPOUSE,
    REMINDER_TO_ADD_KID_AFTER_72_HOURS,
    REMINDER_ADD_KID,
    COMMENT_ON_MOMENT,
    REACTION_ON_MOMENT,
    LAUGH_REACTION_ON_MOMENT,
    SAD_REACTION_ON_MOMENT,
    LOVE_REACTION_ON_MOMENT,
    IMPORTANT_MOMENT,
    REMINDER_TO_ADD_SPOUSE_AFTER_72_HOURS,
    ADD_OTHER_PARENT,
    REMINDER_ADD_OTHER_PARENT,
    OTHER_PARENT_INVITATION,
    REMINDER_OTHER_PARENT_INVITATION,
    FINAL_REMINDER_OTHER_PARENT_INVITATION,
    OTHER_PARENT_ACCEPTED_INVITATION,
    PARENT_DELETED_ACCOUNT,
    PARENT_DEACTIVATED_ACCOUNT,
    PARENT_REACTIVATED_ACCOUNT,
    ADD_FIRST_MOMENT_BY_FIRST_PARENT,
    ADD_FIRST_MOMENT_BY_OTHER_PARENT,
    REMINDER_BOTH_PARENT_ADD_FIRST_MOMENT,
    REMINDER_ADD_MOMENT,
    PARENT_MARKED_MOMENT_IMPORTANT,
    REMINDER_MARKED_MOMENT_IMPORTANT,
    MOMENT_REPORTED_INTIMATION,
    MOMENT_REPORTED_RESOLVED

}